import { decrementCounter, incrementCounter } from '@store/counter/counter.action';
import { getCounterState } from '@store/counter/counter.slice';
import type { NextPage } from 'next';
import Head from 'next/head';
import { useSelector } from 'react-redux';

const Home: NextPage = () => {
	const { value } = useSelector(getCounterState);
	return (
		<div>
			<Head>
				<title>Create Next App</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>

			<main>
				okay
			</main>

			<footer></footer>
		</div>
	);
};

export default Home;
